local tbl = 
{
	backtoLocation = true,
	craftLocType = "Default",
	ephs = 
	{
		[0] = 
		{
		},
		[4] = 
		{
		},
		[8] = 
		{
		},
		[12] = 
		{
		},
		[16] = 
		{
		},
		[20] = 
		{
		},
	},
	filename = "Tank 480 Gear",
	foodId = 1027876,
	foodName = "[HQ] Blood Bouillabaisse",
	glist = 
	{
		
		{
			HQamount = 0,
			amount = 12,
			id = 27736,
			level = 79,
			locnum = 1,
			mapid = 818,
			markers = 
			{
				
				{
					s = "28,16.29",
					x = 330.75,
					y = 346.38,
					z = -256.81,
				},
				
				{
					s = "26.79,14.3",
					x = 267.86,
					y = 336.02,
					z = -354.05,
				},
				
				{
					s = "28,12.69",
					x = 326.03,
					y = 354.53,
					z = -435.69,
				},
				
				{
					s = "31,13.89",
					x = 480.1,
					y = 373.29,
					z = -378.55,
				},
			},
			mobId = 8630,
			mobIds = 
			{
				[8630] = true,
			},
			skip = false,
			str = "Tempest Swallow <<The Tempest>><<79>><<27.5,16.7>>",
			tasktype = "grind",
			timerValue = 947068,
		},
		
		{
			HQamount = 0,
			amount = 12,
			collect = false,
			cordial = false,
			id = 27703,
			job = 16,
			markerid = 8133514,
			markername = "Mapname:[Lakeland] Mapid: 813 X:35 Y:14",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 963814,
		},
		
		{
			HQamount = 0,
			amount = 12,
			collect = false,
			cordial = false,
			id = 27702,
			job = 16,
			markerid = 8151611,
			markername = "Mapname:[Amh Araeng] Mapid: 815 X:16 Y:11",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1106513,
		},
		
		{
			HQamount = 0,
			amount = 8,
			collect = false,
			cordial = false,
			id = 27759,
			job = 17,
			markerid = 8141413,
			markername = "Mapname:[Kholusia] Mapid: 814 X:14 Y:13",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 952864,
		},
		
		{
			HQamount = 0,
			amount = 16,
			collect = false,
			cordial = false,
			id = 27687,
			job = 17,
			markerid = 8131210,
			markername = "Mapname:[Lakeland] Mapid: 813 X:12 Y:10",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 920581,
		},
		
		{
			HQamount = 0,
			amount = 8,
			collect = false,
			cordial = false,
			id = 27783,
			job = 17,
			markerid = 8132431,
			markername = "Mapname:[Lakeland] Mapid: 813 X:24 Y:31",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1023444,
		},
		
		{
			HQamount = 0,
			amount = 3,
			collect = false,
			cordial = false,
			id = 12534,
			job = 16,
			markerid = 3973112,
			markername = "Mapname:[Coerthas Western Highlands] Mapid: 397 X:31 Y:12",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1066659,
		},
		
		{
			HQamount = 0,
			amount = 3,
			collect = false,
			cordial = false,
			id = 12531,
			job = 16,
			markerid = 3971612,
			markername = "Mapname:[Coerthas Western Highlands] Mapid: 397 X:16 Y:12",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1062099,
		},
		
		{
			HQamount = 0,
			amount = 3,
			collect = false,
			cordial = false,
			id = 27817,
			job = 16,
			markerid = 8153022,
			markername = "Mapname:[Amh Araeng] Mapid: 815 X:30 Y:22",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1109150,
		},
	},
	goCollectTurnInAtDone = false,
	listed = 
	{
	},
	normalTimebase = 
	{
		
		{
			collect = false,
			cordial = false,
			id = 0,
			job = 16,
			markerid = 3971612,
			markername = "Mapname:[Coerthas Western Highlands] Mapid: 397 X:16 Y:12",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = false,
			id = 0,
			job = 16,
			markerid = 8153022,
			markername = "Mapname:[Amh Araeng] Mapid: 815 X:30 Y:22",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = false,
			id = 0,
			job = 16,
			markerid = 3973112,
			markername = "Mapname:[Coerthas Western Highlands] Mapid: 397 X:31 Y:12",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = false,
			id = 0,
			job = 17,
			markerid = 8132431,
			markername = "Mapname:[Lakeland] Mapid: 813 X:24 Y:31",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = false,
			id = 0,
			job = 17,
			markerid = 8131210,
			markername = "Mapname:[Lakeland] Mapid: 813 X:12 Y:10",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = false,
			id = 0,
			job = 17,
			markerid = 8141413,
			markername = "Mapname:[Kholusia] Mapid: 814 X:14 Y:13",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = false,
			id = 0,
			job = 16,
			markerid = 8151611,
			markername = "Mapname:[Amh Araeng] Mapid: 815 X:16 Y:11",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = false,
			id = 0,
			job = 16,
			markerid = 8133514,
			markername = "Mapname:[Lakeland] Mapid: 813 X:35 Y:14",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			HQamount = 0,
			amount = 9999999,
			id = 0,
			locnum = 1,
			mapid = 818,
			markers = 
			{
				
				{
					s = "28,16.29",
					x = 330.75,
					y = 346.38,
					z = -256.81,
				},
				
				{
					s = "26.79,14.3",
					x = 267.86,
					y = 336.02,
					z = -354.05,
				},
				
				{
					s = "28,12.69",
					x = 326.03,
					y = 354.53,
					z = -435.69,
				},
				
				{
					s = "31,13.89",
					x = 480.1,
					y = 373.29,
					z = -378.55,
				},
			},
			skip = false,
			str = "Tempest Swallow <<The Tempest>><<79>><<27.5,16.7>>",
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		}, 
		[0] = 
		{
			collect = false,
			cordial = false,
			id = 0,
			job = 16,
			markerid = 8151611,
			markername = "Mapname:[Amh Araeng] Mapid: 815 X:16 Y:11",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skillnum = 6,
			skip = false,
			tasktype = "empty",
		},
	},
	normalType = "Amountbase",
	orders = 
	{
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 18,
			amountInBag = 18,
			amountInBagHQ = 0,
			cmreq = 0,
			collect = false,
			ctrlreq = 0,
			id = 33896,
			ings = 
			{
				[29968] = 4,
				[29969] = 2,
			},
			ingsHQ = 
			{
				[29968] = 0,
				[29969] = 0,
			},
			item = 29958,
			job = 1,
			madaoprofile = "None",
			name = "[80][BSM]Cobalt Alloy Ingot",
			requiredcp = 0,
			reserved = false,
			shards = 
			{
				[14] = 2,
				[17] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = false,
			usePot = false,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 5,
			amountInBag = 5,
			amountInBagHQ = 0,
			cmreq = 0,
			collect = false,
			ctrlreq = 0,
			id = 3854,
			ings = 
			{
				[27759] = 4,
			},
			ingsHQ = 
			{
				[27759] = 0,
			},
			item = 27758,
			job = 5,
			madaoprofile = "None",
			name = "[78][WVR]Dwarven Cotton Thread",
			requiredcp = 0,
			reserved = false,
			shards = 
			{
				[12] = 3,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = false,
			usePot = false,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 2,
			amountInBag = 2,
			amountInBagHQ = 0,
			cmreq = 0,
			collect = false,
			ctrlreq = 0,
			id = 3853,
			ings = 
			{
				[27758] = 3,
			},
			ingsHQ = 
			{
				[27758] = 0,
			},
			item = 27757,
			job = 5,
			madaoprofile = "None",
			name = "[78][WVR]Dwarven Cotton",
			requiredcp = 0,
			reserved = false,
			shards = 
			{
				[12] = 4,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = false,
			usePot = false,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 6,
			amountInBag = 6,
			amountInBagHQ = 0,
			cmreq = 0,
			collect = false,
			ctrlreq = 0,
			id = 33900,
			ings = 
			{
				[29974] = 4,
				[29975] = 2,
			},
			ingsHQ = 
			{
				[29974] = 0,
				[29975] = 0,
			},
			item = 29961,
			job = 5,
			madaoprofile = "None",
			name = "[80][WVR]Duskcourt Cloth",
			requiredcp = 0,
			reserved = false,
			shards = 
			{
				[16] = 2,
				[18] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = false,
			usePot = false,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 24,
			amountInBag = 24,
			amountInBagHQ = 0,
			cmreq = 0,
			collect = false,
			ctrlreq = 0,
			id = 33904,
			ings = 
			{
				[27783] = 1,
				[27812] = 1,
				[28718] = 1,
				[29978] = 3,
			},
			ingsHQ = 
			{
				[27783] = 0,
				[27812] = 0,
				[28718] = 0,
				[29978] = 0,
			},
			item = 29965,
			job = 6,
			madaoprofile = "None",
			name = "[80][ALC]Grade 3 Vitality Alkahest",
			requiredcp = 0,
			reserved = false,
			shards = 
			{
				[18] = 2,
				[19] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = false,
			usePot = false,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 4,
			amountInBag = 4,
			amountInBagHQ = 0,
			cmreq = 0,
			collect = false,
			ctrlreq = 0,
			id = 33901,
			ings = 
			{
				[29976] = 4,
				[29977] = 2,
			},
			ingsHQ = 
			{
				[29976] = 0,
				[29977] = 0,
			},
			item = 29962,
			job = 4,
			madaoprofile = "None",
			name = "[80][LTW]Megalania Leather",
			requiredcp = 0,
			reserved = false,
			shards = 
			{
				[16] = 2,
				[17] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = false,
			usePot = false,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 9,
			amountInBag = 9,
			amountInBagHQ = 0,
			cmreq = 0,
			collect = false,
			ctrlreq = 0,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 33898,
			ings = 
			{
				[29970] = 4,
				[29971] = 2,
			},
			ingsHQ = 
			{
				[29970] = 0,
				[29971] = 0,
			},
			item = 29959,
			job = 3,
			madaoprofile = "None",
			name = "[80][GSM]Purpure Bead",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 0,
			reserved = false,
			shards = 
			{
				[14] = 2,
				[16] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = false,
			usePot = false,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 3,
			amountInBag = 3,
			amountInBagHQ = 0,
			cmreq = 0,
			collect = false,
			ctrlreq = 0,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 3821,
			ings = 
			{
				[12534] = 1,
				[27703] = 4,
			},
			ingsHQ = 
			{
				[12534] = 0,
				[27703] = 0,
			},
			item = 27714,
			job = 1,
			madaoprofile = "None",
			name = "[78][BSM]Dwarven Mythril Ingot",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 0,
			reserved = false,
			shards = 
			{
				[8] = 7,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = false,
			usePot = false,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 3,
			amountInBag = 3,
			amountInBagHQ = 0,
			cmreq = 0,
			collect = false,
			ctrlreq = 0,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 3831,
			ings = 
			{
				[12531] = 1,
				[27702] = 4,
			},
			ingsHQ = 
			{
				[12531] = 0,
				[27702] = 0,
			},
			item = 27715,
			job = 3,
			madaoprofile = "None",
			name = "[78][GSM]Dwarven Mythril Nugget",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 0,
			reserved = false,
			shards = 
			{
				[10] = 7,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = false,
			usePot = false,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 9,
			amountInBag = 9,
			amountInBagHQ = 0,
			cmreq = 0,
			collect = false,
			ctrlreq = 0,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 33899,
			ings = 
			{
				[29972] = 4,
				[29973] = 2,
			},
			ingsHQ = 
			{
				[29972] = 0,
				[29973] = 0,
			},
			item = 29960,
			job = 0,
			madaoprofile = "None",
			name = "[80][CRP]Merbau Lumber",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 0,
			reserved = false,
			shards = 
			{
				[15] = 2,
				[16] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = false,
			usePot = false,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 6,
			amountInBag = 6,
			amountInBagHQ = 0,
			cmreq = 0,
			collect = false,
			ctrlreq = 0,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 3816,
			ings = 
			{
				[27687] = 4,
			},
			ingsHQ = 
			{
				[27687] = 0,
			},
			item = 27693,
			job = 0,
			madaoprofile = "None",
			name = "[78][CRP]Lignum Vitae Lumber",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 0,
			reserved = false,
			shards = 
			{
				[10] = 7,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = false,
			usePot = false,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 4,
			amountInBag = 4,
			amountInBagHQ = 0,
			cmreq = 0,
			collect = false,
			ctrlreq = 0,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 3844,
			ings = 
			{
				[27736] = 4,
				[27817] = 1,
			},
			ingsHQ = 
			{
				[27736] = 0,
				[27817] = 0,
			},
			item = 27742,
			job = 4,
			madaoprofile = "None",
			name = "[78][LTW]Sea Swallow Leather",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 0,
			reserved = false,
			shards = 
			{
				[11] = 7,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = false,
			usePot = false,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 1,
			amountInBag = 1,
			amountInBagHQ = 0,
			cmreq = 2487,
			collect = false,
			ctrlreq = 2609,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 33822,
			ings = 
			{
				[27757] = 1,
				[27814] = 1,
				[29961] = 2,
				[29962] = 2,
				[29965] = 2,
			},
			ingsHQ = 
			{
				[27757] = 0,
				[27814] = 0,
				[29961] = 0,
				[29962] = 0,
				[29965] = 0,
			},
			item = 29425,
			job = 5,
			madaoprofile = "None",
			name = "[80][WVR]Neo-Ishgardian Bottoms of Fending",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 620,
			reserved = false,
			shards = 
			{
				[16] = 2,
				[18] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = true,
			usePot = true,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 1,
			amountInBag = 1,
			amountInBagHQ = 0,
			cmreq = 2487,
			collect = false,
			ctrlreq = 2609,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 33819,
			ings = 
			{
				[27714] = 1,
				[27814] = 1,
				[29959] = 1,
				[29961] = 2,
				[29965] = 2,
			},
			ingsHQ = 
			{
				[27714] = 0,
				[27814] = 0,
				[29959] = 0,
				[29961] = 0,
				[29965] = 0,
			},
			item = 29422,
			job = 5,
			madaoprofile = "None",
			name = "[80][WVR]Neo-Ishgardian Cap of Fending",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 620,
			reserved = false,
			shards = 
			{
				[16] = 2,
				[18] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = true,
			usePot = true,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 1,
			amountInBag = 1,
			amountInBagHQ = 0,
			cmreq = 2487,
			collect = false,
			ctrlreq = 2609,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 33866,
			ings = 
			{
				[27715] = 1,
				[27813] = 1,
				[29958] = 1,
				[29959] = 1,
				[29965] = 1,
			},
			ingsHQ = 
			{
				[27715] = 0,
				[27813] = 0,
				[29958] = 0,
				[29959] = 0,
				[29965] = 0,
			},
			item = 29469,
			job = 3,
			madaoprofile = "None",
			name = "[80][GSM]Neo-Ishgardian Choker of Fending",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 620,
			reserved = false,
			shards = 
			{
				[14] = 2,
				[16] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = true,
			usePot = true,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 1,
			amountInBag = 1,
			amountInBagHQ = 0,
			cmreq = 2487,
			collect = false,
			ctrlreq = 2609,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 33861,
			ings = 
			{
				[27693] = 1,
				[27814] = 1,
				[29960] = 2,
				[29965] = 1,
			},
			ingsHQ = 
			{
				[27693] = 0,
				[27814] = 0,
				[29960] = 0,
				[29965] = 0,
			},
			item = 29464,
			job = 0,
			madaoprofile = "None",
			name = "[80][CRP]Neo-Ishgardian Earring of Fending",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 620,
			reserved = false,
			shards = 
			{
				[15] = 2,
				[16] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = true,
			usePot = true,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 1,
			amountInBag = 1,
			amountInBagHQ = 0,
			cmreq = 2487,
			collect = false,
			ctrlreq = 2609,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 33821,
			ings = 
			{
				[27757] = 1,
				[27814] = 1,
				[29958] = 2,
				[29962] = 1,
				[29965] = 2,
			},
			ingsHQ = 
			{
				[27757] = 0,
				[27814] = 0,
				[29958] = 0,
				[29962] = 0,
				[29965] = 0,
			},
			item = 29424,
			job = 2,
			madaoprofile = "None",
			name = "[80][ARM]Neo-Ishgardian Gauntlets of Fending",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 620,
			reserved = false,
			shards = 
			{
				[15] = 2,
				[17] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = true,
			usePot = true,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 1,
			amountInBag = 1,
			amountInBagHQ = 0,
			cmreq = 2487,
			collect = false,
			ctrlreq = 2609,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 33807,
			ings = 
			{
				[27715] = 1,
				[27814] = 1,
				[29958] = 2,
				[29960] = 2,
				[29965] = 2,
			},
			ingsHQ = 
			{
				[27715] = 0,
				[27814] = 0,
				[29958] = 0,
				[29960] = 0,
				[29965] = 0,
			},
			item = 29410,
			job = 1,
			madaoprofile = "None",
			name = "[80][BSM]Neo-Ishgardian Greatsword",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 620,
			reserved = false,
			shards = 
			{
				[14] = 2,
				[17] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = true,
			usePot = true,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 1,
			amountInBag = 1,
			amountInBagHQ = 0,
			cmreq = 2487,
			collect = false,
			ctrlreq = 2609,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 33803,
			ings = 
			{
				[27742] = 1,
				[27814] = 1,
				[29958] = 2,
				[29959] = 2,
				[29965] = 2,
			},
			ingsHQ = 
			{
				[27742] = 0,
				[27814] = 0,
				[29958] = 0,
				[29959] = 0,
				[29965] = 0,
			},
			item = 29406,
			job = 1,
			madaoprofile = "None",
			name = "[80][BSM]Neo-Ishgardian Labrys",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 620,
			reserved = false,
			shards = 
			{
				[14] = 2,
				[17] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = true,
			usePot = true,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 1,
			amountInBag = 1,
			amountInBagHQ = 0,
			cmreq = 2487,
			collect = false,
			ctrlreq = 2609,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 33816,
			ings = 
			{
				[27714] = 1,
				[27814] = 1,
				[29958] = 2,
				[29959] = 2,
				[29965] = 2,
			},
			ingsHQ = 
			{
				[27714] = 0,
				[27814] = 0,
				[29958] = 0,
				[29959] = 0,
				[29965] = 0,
			},
			item = 29419,
			job = 1,
			madaoprofile = "None",
			name = "[80][BSM]Neo-Ishgardian Manatrigger",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 620,
			reserved = false,
			shards = 
			{
				[14] = 2,
				[17] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = true,
			usePot = true,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 1,
			amountInBag = 1,
			amountInBagHQ = 0,
			cmreq = 2487,
			collect = false,
			ctrlreq = 2609,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 33824,
			ings = 
			{
				[27742] = 1,
				[27815] = 1,
				[29958] = 1,
				[29960] = 1,
				[29965] = 1,
			},
			ingsHQ = 
			{
				[27742] = 0,
				[27815] = 0,
				[29958] = 0,
				[29960] = 0,
				[29965] = 0,
			},
			item = 29427,
			job = 2,
			madaoprofile = "None",
			name = "[80][ARM]Neo-Ishgardian Plate Belt of Fending",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 620,
			reserved = false,
			shards = 
			{
				[15] = 2,
				[17] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = true,
			usePot = true,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 2,
			amountInBag = 1,
			amountInBagHQ = 0,
			cmreq = 2487,
			collect = false,
			ctrlreq = 2609,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 33876,
			ings = 
			{
				[27693] = 1,
				[27815] = 1,
				[29959] = 1,
				[29960] = 1,
				[29965] = 1,
			},
			ingsHQ = 
			{
				[27693] = 0,
				[27815] = 0,
				[29959] = 0,
				[29960] = 0,
				[29965] = 0,
			},
			item = 29479,
			job = 0,
			madaoprofile = "None",
			name = "[80][CRP]Neo-Ishgardian Ring of Fending",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 620,
			reserved = false,
			shards = 
			{
				[15] = 2,
				[16] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = true,
			usePot = true,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 1,
			amountInBag = 1,
			amountInBagHQ = 0,
			cmreq = 2487,
			collect = false,
			ctrlreq = 2609,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 33818,
			ings = 
			{
				[29958] = 1,
				[29960] = 1,
				[29965] = 1,
			},
			ingsHQ = 
			{
				[29958] = 0,
				[29960] = 0,
				[29965] = 0,
			},
			item = 29421,
			job = 2,
			madaoprofile = "None",
			name = "[80][ARM]Neo-Ishgardian Shield",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 620,
			reserved = false,
			shards = 
			{
				[15] = 2,
				[17] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = true,
			usePot = true,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 1,
			amountInBag = 1,
			amountInBagHQ = 0,
			cmreq = 2487,
			collect = false,
			ctrlreq = 2609,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 33823,
			ings = 
			{
				[27693] = 1,
				[27813] = 1,
				[29958] = 2,
				[29962] = 1,
				[29965] = 2,
			},
			ingsHQ = 
			{
				[27693] = 0,
				[27813] = 0,
				[29958] = 0,
				[29962] = 0,
				[29965] = 0,
			},
			item = 29426,
			job = 2,
			madaoprofile = "None",
			name = "[80][ARM]Neo-Ishgardian Sollerets of Fending",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 620,
			reserved = false,
			shards = 
			{
				[15] = 2,
				[17] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = true,
			usePot = true,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 1,
			amountInBag = 1,
			amountInBagHQ = 0,
			cmreq = 2487,
			collect = false,
			ctrlreq = 2609,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 33801,
			ings = 
			{
				[27714] = 1,
				[27814] = 1,
				[29958] = 2,
				[29965] = 1,
			},
			ingsHQ = 
			{
				[27714] = 0,
				[27814] = 0,
				[29958] = 0,
				[29965] = 0,
			},
			item = 29404,
			job = 1,
			madaoprofile = "None",
			name = "[80][BSM]Neo-Ishgardian Sword",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 620,
			reserved = false,
			shards = 
			{
				[14] = 2,
				[17] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = true,
			usePot = true,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 1,
			amountInBag = 1,
			amountInBagHQ = 0,
			cmreq = 2487,
			collect = false,
			ctrlreq = 2609,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 33820,
			ings = 
			{
				[27742] = 1,
				[27813] = 1,
				[29958] = 2,
				[29961] = 2,
				[29965] = 2,
			},
			ingsHQ = 
			{
				[27742] = 0,
				[27813] = 0,
				[29958] = 0,
				[29961] = 0,
				[29965] = 0,
			},
			item = 29423,
			job = 2,
			madaoprofile = "None",
			name = "[80][ARM]Neo-Ishgardian Top of Fending",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 620,
			reserved = false,
			shards = 
			{
				[15] = 2,
				[17] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = true,
			usePot = true,
			useQuickIfPossible = false,
			usequick = false,
		},
		
		{
			HQingAuto = false,
			HQingAutoVal = 35,
			amount = 1,
			amountInBag = 1,
			amountInBagHQ = 0,
			cmreq = 2487,
			collect = false,
			ctrlreq = 2609,
			foodId = 1027876,
			foodName = "[HQ] Blood Bouillabaisse",
			id = 33871,
			ings = 
			{
				[27715] = 1,
				[27813] = 1,
				[29959] = 1,
				[29960] = 1,
				[29965] = 1,
			},
			ingsHQ = 
			{
				[27715] = 0,
				[27813] = 0,
				[29959] = 0,
				[29960] = 0,
				[29965] = 0,
			},
			item = 29474,
			job = 3,
			madaoprofile = "None",
			name = "[80][GSM]Neo-Ishgardian Wristbands of Fending",
			potId = "1027959",
			potName = "[HQ] Cunning Craftsman's Syrup",
			requiredcp = 620,
			reserved = false,
			shards = 
			{
				[14] = 2,
				[16] = 2,
			},
			skillprofile = "None",
			skilltype = 2,
			skip = false,
			useFood = true,
			usePot = true,
			useQuickIfPossible = false,
			usequick = false,
		},
	},
	potId = "1027959",
	potName = "[HQ] Cunning Craftsman's Syrup",
	profileRepeat = false,
	profileType = "OneTime",
	skill = 
	{
		dskName = "None",
		skeName = "None",
		skillType = "Auto",
	},
	unspoil = 
	{
		
		{
			HQamount = 0,
			amount = 16,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29976,
			job = 16,
			mapid = 815,
			markerid = 8152008,
			name = "Ashen Alumen",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 6,
			skip = false,
			slot = 2,
			timeChecks = 
			{
				[10] = true,
				[11] = true,
				[22] = true,
				[23] = true,
			},
			timeoks = 
			{
				10,
				11,
				22,
				23,
			},
			x = 20,
			y = 8,
		},
		
		{
			HQamount = 0,
			amount = 24,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29974,
			job = 17,
			mapid = 815,
			markerid = 8153233,
			name = "Duskblooms",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 6,
			skip = false,
			slot = 4,
			timeChecks = 
			{
				[4] = true,
				[5] = true,
				[16] = true,
				[17] = true,
			},
			timeoks = 
			{
				4,
				5,
				16,
				17,
			},
			x = 32,
			y = 33,
		},
		
		{
			HQamount = 0,
			amount = 68,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29968,
			job = 16,
			mapid = 813,
			markerid = 8130433,
			name = "Fireheart Cobalt",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 6,
			skip = false,
			slot = 6,
			timeChecks = 
			{
				[2] = true,
				[3] = true,
				[14] = true,
				[15] = true,
			},
			timeoks = 
			{
				2,
				3,
				14,
				15,
			},
			x = 4,
			y = 33,
		},
		
		{
			HQamount = 0,
			amount = 24,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29978,
			job = 17,
			mapid = 814,
			markerid = 8142821,
			name = "Imperial Fern",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 6,
			skip = false,
			slot = 3,
			timeChecks = 
			{
				true, 
				[0] = true,
				[12] = true,
				[13] = true,
			},
			timeoks = 
			{
				0,
				1,
				12,
				13,
			},
			x = 28,
			y = 21,
		},
		
		{
			HQamount = 0,
			amount = 36,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29972,
			job = 17,
			mapid = 816,
			markerid = 8163627,
			name = "Merbau Log",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 6,
			skip = false,
			slot = 6,
			timeChecks = 
			{
				[8] = true,
				[9] = true,
				[20] = true,
				[21] = true,
			},
			timeoks = 
			{
				8,
				9,
				20,
				21,
			},
			x = 36,
			y = 27,
		},
		
		{
			HQamount = 0,
			amount = 36,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29970,
			job = 16,
			mapid = 818,
			markerid = 8183431,
			name = "Purpure Shell Chip",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 6,
			skip = false,
			slot = 1,
			timeChecks = 
			{
				[6] = true,
				[7] = true,
				[18] = true,
				[19] = true,
			},
			timeoks = 
			{
				6,
				7,
				18,
				19,
			},
			x = 34,
			y = 31,
		},
	},
	unspoilTimeline = 
	{
		
		{
			29978,
		},
		
		{
			29968,
		},
		
		{
			29968,
		},
		
		{
			29974,
		},
		
		{
			29974,
		},
		
		{
			29970,
		},
		
		{
			29970,
		},
		
		{
			29972,
		},
		
		{
			29972,
		},
		
		{
			29976,
		},
		
		{
			29976,
		},
		
		{
			29978,
		},
		
		{
			29978,
		},
		
		{
			29968,
		},
		
		{
			29968,
		},
		
		{
			29974,
		},
		
		{
			29974,
		},
		
		{
			29970,
		},
		
		{
			29970,
		},
		
		{
			29972,
		},
		
		{
			29972,
		},
		
		{
			29976,
		},
		
		{
			29976,
		}, 
		[0] = 
		{
			29978,
		},
	},
	useFood = true,
	usePot = true,
}



return tbl