local tbl = 
{
	eph = 
	{
	},
	ephs = 
	{
		[0] = 
		{
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				cordial = true,
				crystal = 0,
				crystalId = 11,
				gatherNormalDo = false,
				id = 30591,
				job = 16,
				mapid = 817,
				mapname = "The Rak'tika Greatwood X:26 Y:30",
				markerid = 8172630,
				name = "Thunder Rock",
				okgp = 0,
				sand = 30590,
				shard = 5,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skillnum = 3,
				skip = false,
				sname = "Levinstrike Aethersand",
				submarkerid = 8172529,
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				cordial = true,
				crystal = 0,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27542,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:13",
				markerid = 8162013,
				name = "Voeburt Bichir",
				okgp = 0,
				sand = 27811,
				shard = 7,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skillnum = 4,
				skip = false,
				sname = "Chiaroglow Aethersand",
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				cordial = true,
				crystal = 1,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27805,
				job = 16,
				mapid = 817,
				mapname = "The Rak'tika Greatwood X:26 Y:30",
				markerid = 8172630,
				name = "Gale Rock",
				okgp = 700,
				sand = 27811,
				shard = 7,
				skillname = "Collective_Default.lua",
				skillnum = 2,
				skip = false,
				sname = "Chiaroglow Aethersand",
				submarkerid = 8172529,
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27543,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:22",
				markerid = 8162022,
				name = "Poecilia",
				okgp = 0,
				sand = 27812,
				shard = 7,
				skillname = "Collective_Default.lua",
				skillnum = 2,
				skip = true,
				sname = "Scuroglow Aethersand",
				useGift = true,
			},
		},
		[4] = 
		{
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				cordial = true,
				crystal = 0,
				crystalId = 12,
				gatherNormalDo = false,
				id = 30592,
				job = 17,
				mapid = 817,
				mapname = "The Rak'tika Greatwood X:27 Y:24",
				markerid = 8172724,
				name = "Levin Mint",
				okgp = 0,
				sand = 30590,
				shard = 6,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skillnum = 3,
				skip = false,
				sname = "Levinstrike Aethersand",
				submarkerid = 8172725,
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				cordial = true,
				crystal = 0,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27542,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:13",
				markerid = 8162013,
				name = "Voeburt Bichir",
				okgp = 0,
				sand = 27811,
				shard = 7,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skip = false,
				sname = "Chiaroglow Aethersand",
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 10,
				gatherNormalDo = false,
				id = 27809,
				job = 17,
				mapid = 817,
				mapname = "The Rak'tika Greatwood X:27 Y:24",
				markerid = 8172724,
				name = "Sweet Marjoram",
				okgp = 700,
				sand = 27812,
				shard = 4,
				skillname = "Collective_Default.lua",
				skillnum = 2,
				skip = true,
				sname = "Scuroglow Aethersand",
				submarkerid = 8172725,
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27543,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:22",
				markerid = 8162022,
				name = "Poecilia",
				okgp = 0,
				sand = 27812,
				shard = 7,
				skillname = "Collective_Default.lua",
				skip = true,
				sname = "Scuroglow Aethersand",
				useGift = true,
			},
		},
		[8] = 
		{
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				cordial = true,
				crystal = 0,
				crystalId = 11,
				gatherNormalDo = false,
				id = 30591,
				job = 16,
				mapid = 813,
				mapname = "Lakeland X:37 Y:15",
				markerid = 8133715,
				name = "Thunder Rock",
				okgp = 0,
				sand = 30590,
				shard = 5,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skillnum = 3,
				skip = false,
				sname = "Levinstrike Aethersand",
				submarkerid = 8133514,
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 12,
				gatherNormalDo = false,
				id = 27806,
				job = 16,
				mapid = 813,
				mapname = "Lakeland X:37 Y:15",
				markerid = 8133715,
				name = "Solarite",
				okgp = 700,
				sand = 27812,
				shard = 6,
				skillname = "Collective_Default.lua",
				skillnum = 2,
				skip = true,
				sname = "Scuroglow Aethersand",
				submarkerid = 8133514,
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27543,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:22",
				markerid = 8162022,
				name = "Poecilia",
				okgp = 0,
				sand = 27812,
				shard = 7,
				skillname = "Collective_Default.lua",
				skillnum = 2,
				skip = true,
				sname = "Scuroglow Aethersand",
				useGift = true,
			},
		},
		[12] = 
		{
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				cordial = true,
				crystal = 0,
				crystalId = 12,
				gatherNormalDo = false,
				id = 30592,
				job = 17,
				mapid = 813,
				mapname = "Lakeland X:25 Y:30",
				markerid = 8132530,
				name = "Levin Mint",
				okgp = 0,
				sand = 30590,
				shard = 6,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skillnum = 3,
				skip = false,
				sname = "Levinstrike Aethersand",
				submarkerid = 8132431,
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				cordial = true,
				crystal = 1,
				crystalId = 9,
				gatherNormalDo = false,
				id = 27810,
				job = 17,
				mapid = 813,
				mapname = "Lakeland X:25 Y:30",
				markerid = 8132530,
				name = "Bog Sage",
				okgp = 700,
				sand = 27814,
				shard = 3,
				skillname = "Collective_Default.lua",
				skillnum = 2,
				skip = false,
				sname = "Agewood Aethersand",
				submarkerid = 8132431,
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				cordial = true,
				crystal = 0,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27542,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:13",
				markerid = 8162013,
				name = "Voeburt Bichir",
				okgp = 0,
				sand = 27811,
				shard = 7,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skip = false,
				sname = "Chiaroglow Aethersand",
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27543,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:22",
				markerid = 8162022,
				name = "Poecilia",
				okgp = 0,
				sand = 27812,
				shard = 7,
				skillname = "Collective_Default.lua",
				skip = true,
				sname = "Scuroglow Aethersand",
				useGift = true,
			},
		},
		[16] = 
		{
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				cordial = true,
				crystal = 0,
				crystalId = 11,
				gatherNormalDo = false,
				id = 30591,
				job = 16,
				mapid = 814,
				mapname = "Kholusia X:22 Y:18",
				markerid = 8142218,
				name = "Thunder Rock",
				okgp = 0,
				sand = 30590,
				shard = 5,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skillnum = 3,
				skip = false,
				sname = "Levinstrike Aethersand",
				submarkerid = 8142118,
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				cordial = true,
				crystal = 0,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27542,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:13",
				markerid = 8162013,
				name = "Voeburt Bichir",
				okgp = 0,
				sand = 27811,
				shard = 7,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skip = false,
				sname = "Chiaroglow Aethersand",
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27543,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:22",
				markerid = 8162022,
				name = "Poecilia",
				okgp = 0,
				sand = 27812,
				shard = 7,
				skillname = "Collective_Default.lua",
				skip = true,
				sname = "Scuroglow Aethersand",
				useGift = true,
			},
		},
		[20] = 
		{
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				cordial = true,
				crystal = 0,
				crystalId = 12,
				gatherNormalDo = false,
				id = 30592,
				job = 17,
				mapid = 814,
				mapname = "Kholusia X:13 Y:13",
				markerid = 8141313,
				name = "Levin Mint",
				okgp = 0,
				sand = 30590,
				shard = 6,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skillnum = 3,
				skip = false,
				sname = "Levinstrike Aethersand",
				submarkerid = 8141413,
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				cordial = true,
				crystal = 1,
				crystalId = 11,
				gatherNormalDo = false,
				id = 27808,
				job = 17,
				mapid = 814,
				mapname = "Kholusia X:13 Y:13",
				markerid = 8141313,
				name = "White Clay",
				okgp = 700,
				sand = 27811,
				shard = 5,
				skillname = "Collective_Default.lua",
				skillnum = 2,
				skip = false,
				sname = "Chiaroglow Aethersand",
				submarkerid = 8141413,
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				cordial = true,
				crystal = 0,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27542,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:13",
				markerid = 8162013,
				name = "Voeburt Bichir",
				okgp = 0,
				sand = 27811,
				shard = 7,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skip = false,
				sname = "Chiaroglow Aethersand",
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27543,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:22",
				markerid = 8162022,
				name = "Poecilia",
				okgp = 0,
				sand = 27812,
				shard = 7,
				skillname = "Collective_Default.lua",
				skip = true,
				sname = "Scuroglow Aethersand",
				useGift = true,
			},
		},
	},
	filename = "Sands",
	glist = 
	{
	},
	normalTimebase = 
	{
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		}, 
		[0] = 
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
	},
	normalType = "Timebase",
	orders = 
	{
	},
	unspoil = 
	{
		
		{
			HQamount = 0,
			amount = 20,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 30486,
			job = 16,
			mapid = 813,
			markerid = 8130433,
			name = "Brashgold Ore",
			okgp = 0,
			reserve = false,
			skillname = "Pick Clean + Blessed + Bountiful.lua",
			skillnum = 15,
			skip = false,
			slot = 7,
			timeChecks = 
			{
				[2] = true,
				[3] = true,
				[14] = true,
				[15] = true,
			},
			timeoks = 
			{
				2,
				3,
				14,
				15,
			},
			x = 4,
			y = 33,
		},
		
		{
			HQamount = 0,
			amount = 20,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29968,
			job = 16,
			mapid = 813,
			markerid = 8130433,
			name = "Fireheart Cobalt",
			okgp = 0,
			reserve = false,
			skillname = "Pick Clean + Blessed + Bountiful.lua",
			skillnum = 15,
			skip = false,
			slot = 6,
			timeChecks = 
			{
				[2] = true,
				[3] = true,
				[14] = true,
				[15] = true,
			},
			timeoks = 
			{
				2,
				3,
				14,
				15,
			},
			x = 4,
			y = 33,
		},
	},
	unspoilTimeline = 
	{
		
		{
		},
		
		{
			30486,
			29968,
		},
		
		{
			30486,
			29968,
		},
		
		{
		},
		
		{
		},
		
		{
		},
		
		{
		},
		
		{
		},
		
		{
		},
		
		{
		},
		
		{
		},
		
		{
		},
		
		{
		},
		
		{
			30486,
			29968,
		},
		
		{
			30486,
			29968,
		},
		
		{
		},
		
		{
		},
		
		{
		},
		
		{
		},
		
		{
		},
		
		{
		},
		
		{
		},
		
		{
		}, 
		[0] = 
		{
		},
	},
}



return tbl