local tbl = 
{
	eph = 
	{
	},
	ephs = 
	{
		[0] = 
		{
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 0,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27542,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:13",
				markerid = 8162013,
				name = "Voeburt Bichir",
				okgp = 0,
				sand = 27811,
				shard = 7,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skip = true,
				sname = "Chiaroglow Aethersand",
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 0,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27805,
				job = 16,
				mapid = 817,
				mapname = "The Rak'tika Greatwood X:26 Y:30",
				markerid = 8172630,
				name = "Gale Rock",
				okgp = 0,
				sand = 27811,
				shard = 7,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skillnum = 3,
				skip = true,
				sname = "Chiaroglow Aethersand",
				submarkerid = 8172529,
				useGift = true,
			},
		},
		[4] = 
		{
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 0,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27542,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:13",
				markerid = 8162013,
				name = "Voeburt Bichir",
				okgp = 0,
				sand = 27811,
				shard = 7,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skip = false,
				sname = "Chiaroglow Aethersand",
				useGift = true,
			},
		},
		[8] = 
		{
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 0,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27542,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:13",
				markerid = 8162013,
				name = "Voeburt Bichir",
				okgp = 0,
				sand = 27811,
				shard = 7,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skip = true,
				sname = "Chiaroglow Aethersand",
				useGift = true,
			},
		},
		[12] = 
		{
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 0,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27542,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:13",
				markerid = 8162013,
				name = "Voeburt Bichir",
				okgp = 0,
				sand = 27811,
				shard = 7,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skip = true,
				sname = "Chiaroglow Aethersand",
				useGift = true,
			},
		},
		[16] = 
		{
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 0,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27542,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:13",
				markerid = 8162013,
				name = "Voeburt Bichir",
				okgp = 0,
				sand = 27811,
				shard = 7,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skip = true,
				sname = "Chiaroglow Aethersand",
				useGift = true,
			},
		},
		[20] = 
		{
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 0,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27542,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:13",
				markerid = 8162013,
				name = "Voeburt Bichir",
				okgp = 0,
				sand = 27811,
				shard = 7,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skip = true,
				sname = "Chiaroglow Aethersand",
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 0,
				crystalId = 11,
				gatherNormalDo = false,
				id = 27808,
				job = 17,
				mapid = 814,
				mapname = "Kholusia X:13 Y:13",
				markerid = 8141313,
				name = "White Clay",
				okgp = 0,
				sand = 27811,
				shard = 5,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skillnum = 3,
				skip = true,
				sname = "Chiaroglow Aethersand",
				submarkerid = 8141413,
				useGift = true,
			},
		},
	},
	filename = "Raid",
	glist = 
	{
		
		{
			HQamount = 0,
			amount = 0,
			collect = false,
			cordial = false,
			id = 27820,
			job = 17,
			markerid = 8133525,
			markername = "Mapname:[Lakeland] Mapid: 813 X:35 Y:25",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			tasktype = "gather",
			timerValue = 1038395,
		},
		
		{
			HQamount = 0,
			amount = 898,
			collect = false,
			cordial = false,
			id = 27825,
			job = 17,
			markerid = 8161122,
			markername = "Mapname:[Il Mheg] Mapid: 816 X:11 Y:22",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			tasktype = "gather",
			timerValue = 976595,
		},
		
		{
			HQamount = 0,
			amount = 500,
			collect = false,
			cordial = false,
			id = 4830,
			job = 17,
			markerid = 1412520,
			markername = "Mapname:[Central Thanalan] Mapid: 141 X:25 Y:20",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			tasktype = "gather",
			timerValue = 1184299,
		},
		
		{
			HQamount = 0,
			amount = 400,
			id = 27852,
			level = 76,
			locnum = 1,
			mapid = 815,
			markers = 
			{
				
				{
					s = "15.5,13.3",
					x = -294.94,
					y = 10.52,
					z = -404.16,
				},
				
				{
					s = "17.89,11.6",
					x = -175.37,
					y = 35.56,
					z = -491.66,
				},
				
				{
					s = "19.7,13.1",
					x = -86.21,
					y = 34.81,
					z = -416.69,
				},
			},
			mobId = 8552,
			mobIds = 
			{
				[8552] = true,
				[8553] = true,
			},
			skip = false,
			str = "Ovim Billy <<Amh Araeng>><<76>><<15.5,13.8>>",
			tasktype = "grind",
			timerValue = 1176233,
		},
		
		{
			HQamount = 0,
			amount = 500,
			collect = false,
			cordial = false,
			id = 27785,
			job = 17,
			markerid = 8132431,
			markername = "Mapname:[Lakeland] Mapid: 813 X:24 Y:31",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			tasktype = "gather",
			timerValue = 988543,
		},
		
		{
			HQamount = 0,
			amount = 500,
			collect = false,
			cordial = false,
			id = 27784,
			job = 17,
			markerid = 8132431,
			markername = "Mapname:[Lakeland] Mapid: 813 X:24 Y:31",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			tasktype = "gather",
			timerValue = 1005646,
		},
		
		{
			HQamount = 0,
			amount = 100,
			collect = false,
			cordial = false,
			id = 4843,
			job = 17,
			markerid = 1462007,
			markername = "Mapname:[Southern Thanalan] Mapid: 146 X:20 Y:7",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			tasktype = "gather",
			timerValue = 969188,
		},
		
		{
			HQamount = 0,
			amount = 100,
			collect = false,
			cordial = false,
			id = 12878,
			job = 17,
			markerid = 3983620,
			markername = "Mapname:[The Dravanian Forelands] Mapid: 398 X:36 Y:20",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			tasktype = "gather",
			timerValue = 1124101,
		},
		
		{
			HQamount = 0,
			amount = 100,
			collect = false,
			cordial = false,
			id = 27829,
			job = 17,
			markerid = 8171427,
			markername = "Mapname:[The Rak'tika] Mapid: 817 X:14 Y:27",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			tasktype = "gather",
			timerValue = 1135298,
		},
	},
	normalTimebase = 
	{
		
		{
			collect = false,
			cordial = false,
			id = 0,
			job = 17,
			markerid = 8161122,
			markername = "Mapname:[Il Mheg] Mapid: 816 X:11 Y:22",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skillnum = 6,
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		}, 
		[0] = 
		{
			collect = false,
			cordial = false,
			id = 0,
			job = 17,
			markerid = 8133525,
			markername = "Mapname:[Lakeland] Mapid: 813 X:35 Y:25",
			notinlistcaseid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
	},
	normalType = "Amountbase",
	orders = 
	{
	},
	unspoil = 
	{
		
		{
			HQamount = 0,
			amount = 0,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29976,
			job = 16,
			mapid = 815,
			markerid = 8152008,
			name = "Ashen Alumen",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			slot = 2,
			timeChecks = 
			{
				[10] = true,
				[11] = true,
				[22] = true,
				[23] = true,
			},
			timeoks = 
			{
				10,
				11,
				22,
				23,
			},
			x = 20,
			y = 8,
		},
		
		{
			HQamount = 0,
			amount = 0,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29972,
			job = 17,
			mapid = 816,
			markerid = 8163627,
			name = "Merbau Log",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			slot = 6,
			timeChecks = 
			{
				[8] = true,
				[9] = true,
				[20] = true,
				[21] = true,
			},
			timeoks = 
			{
				8,
				9,
				20,
				21,
			},
			x = 36,
			y = 27,
		},
		
		{
			HQamount = 0,
			amount = 0,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29970,
			job = 16,
			mapid = 818,
			markerid = 8183431,
			name = "Purpure Shell Chip",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			slot = 1,
			timeChecks = 
			{
				[6] = true,
				[7] = true,
				[18] = true,
				[19] = true,
			},
			timeoks = 
			{
				6,
				7,
				18,
				19,
			},
			x = 34,
			y = 31,
		},
		
		{
			HQamount = 0,
			amount = 0,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29974,
			job = 17,
			mapid = 815,
			markerid = 8153233,
			name = "Duskblooms",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			slot = 4,
			timeChecks = 
			{
				[4] = true,
				[5] = true,
				[16] = true,
				[17] = true,
			},
			timeoks = 
			{
				4,
				5,
				16,
				17,
			},
			x = 32,
			y = 33,
		},
		
		{
			HQamount = 0,
			amount = 0,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29968,
			job = 16,
			mapid = 813,
			markerid = 8130433,
			name = "Fireheart Cobalt",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			slot = 6,
			timeChecks = 
			{
				[2] = true,
				[3] = true,
				[14] = true,
				[15] = true,
			},
			timeoks = 
			{
				2,
				3,
				14,
				15,
			},
			x = 4,
			y = 33,
		},
		
		{
			HQamount = 0,
			amount = 0,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29978,
			job = 17,
			mapid = 814,
			markerid = 8142821,
			name = "Imperial Fern",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			slot = 3,
			timeChecks = 
			{
				true, 
				[0] = true,
				[12] = true,
				[13] = true,
			},
			timeoks = 
			{
				0,
				1,
				12,
				13,
			},
			x = 28,
			y = 21,
		},
		
		{
			HQamount = 0,
			amount = 0,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = false,
			hold = false,
			id = 27828,
			job = 17,
			mapid = 817,
			markerid = 8173421,
			name = "Mist Spinach",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = false,
			slot = 6,
			timeChecks = 
			{
				true, 
				[0] = true,
				[12] = true,
				[13] = true,
			},
			timeoks = 
			{
				0,
				1,
				12,
				13,
			},
			x = 34,
			y = 21,
		},
	},
	unspoilTimeline = 
	{
		
		{
			29978,
			27828,
		},
		
		{
			29968,
		},
		
		{
			29968,
		},
		
		{
			29974,
		},
		
		{
			29974,
		},
		
		{
			29970,
		},
		
		{
			29970,
		},
		
		{
			29972,
		},
		
		{
			29972,
		},
		
		{
			29976,
		},
		
		{
			29976,
		},
		
		{
			29978,
			27828,
		},
		
		{
			29978,
			27828,
		},
		
		{
			29968,
		},
		
		{
			29968,
		},
		
		{
			29974,
		},
		
		{
			29974,
		},
		
		{
			29970,
		},
		
		{
			29970,
		},
		
		{
			29972,
		},
		
		{
			29972,
		},
		
		{
			29976,
		},
		
		{
			29976,
		}, 
		[0] = 
		{
			29978,
			27828,
		},
	},
}



return tbl