local tbl = 
{
	eph = 
	{
	},
	ephs = 
	{
		[0] = 
		{
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 0,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27542,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:13",
				markerid = 8162013,
				name = "Voeburt Bichir",
				okgp = 0,
				sand = 27811,
				shard = 7,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skip = false,
				sname = "Chiaroglow Aethersand",
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27805,
				job = 16,
				mapid = 817,
				mapname = "The Rak'tika Greatwood X:26 Y:30",
				markerid = 8172630,
				name = "Gale Rock",
				okgp = 700,
				sand = 27811,
				shard = 7,
				skillname = "Collective_Default.lua",
				skillnum = 2,
				skip = false,
				sname = "Chiaroglow Aethersand",
				submarkerid = 8172529,
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27543,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:22",
				markerid = 8162022,
				name = "Poecilia",
				okgp = 0,
				sand = 27812,
				shard = 7,
				skillname = "Collective_Default.lua",
				skip = false,
				sname = "Scuroglow Aethersand",
				useGift = true,
			},
		},
		[4] = 
		{
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 0,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27542,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:13",
				markerid = 8162013,
				name = "Voeburt Bichir",
				okgp = 0,
				sand = 27811,
				shard = 7,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skip = false,
				sname = "Chiaroglow Aethersand",
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 10,
				gatherNormalDo = false,
				id = 27809,
				job = 17,
				mapid = 817,
				mapname = "The Rak'tika Greatwood X:27 Y:24",
				markerid = 8172724,
				name = "Sweet Marjoram",
				okgp = 700,
				sand = 27812,
				shard = 4,
				skillname = "Collective_Default.lua",
				skillnum = 2,
				skip = true,
				sname = "Scuroglow Aethersand",
				submarkerid = 8172725,
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27543,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:22",
				markerid = 8162022,
				name = "Poecilia",
				okgp = 0,
				sand = 27812,
				shard = 7,
				skillname = "Collective_Default.lua",
				skip = true,
				sname = "Scuroglow Aethersand",
				useGift = true,
			},
		},
		[8] = 
		{
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 12,
				gatherNormalDo = false,
				id = 27806,
				job = 16,
				mapid = 813,
				mapname = "Lakeland X:37 Y:15",
				markerid = 8133715,
				name = "Solarite",
				okgp = 700,
				sand = 27812,
				shard = 6,
				skillname = "Collective_Default.lua",
				skillnum = 2,
				skip = false,
				sname = "Scuroglow Aethersand",
				submarkerid = 8133514,
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27543,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:22",
				markerid = 8162022,
				name = "Poecilia",
				okgp = 0,
				sand = 27812,
				shard = 7,
				skillname = "Collective_Default.lua",
				skillnum = 2,
				skip = false,
				sname = "Scuroglow Aethersand",
				useGift = true,
			},
		},
		[12] = 
		{
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 9,
				gatherNormalDo = false,
				id = 27810,
				job = 17,
				mapid = 813,
				mapname = "Lakeland X:25 Y:30",
				markerid = 8132530,
				name = "Bog Sage",
				okgp = 700,
				sand = 27814,
				shard = 3,
				skillname = "Collective_Default.lua",
				skillnum = 2,
				skip = false,
				sname = "Agewood Aethersand",
				submarkerid = 8132431,
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 0,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27542,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:13",
				markerid = 8162013,
				name = "Voeburt Bichir",
				okgp = 0,
				sand = 27811,
				shard = 7,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skip = false,
				sname = "Chiaroglow Aethersand",
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27543,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:22",
				markerid = 8162022,
				name = "Poecilia",
				okgp = 0,
				sand = 27812,
				shard = 7,
				skillname = "Collective_Default.lua",
				skip = true,
				sname = "Scuroglow Aethersand",
				useGift = true,
			},
		},
		[16] = 
		{
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 0,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27542,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:13",
				markerid = 8162013,
				name = "Voeburt Bichir",
				okgp = 0,
				sand = 27811,
				shard = 7,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skip = false,
				sname = "Chiaroglow Aethersand",
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27543,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:22",
				markerid = 8162022,
				name = "Poecilia",
				okgp = 0,
				sand = 27812,
				shard = 7,
				skillname = "Collective_Default.lua",
				skip = true,
				sname = "Scuroglow Aethersand",
				useGift = true,
			},
		},
		[20] = 
		{
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 11,
				gatherNormalDo = false,
				id = 27808,
				job = 17,
				mapid = 814,
				mapname = "Kholusia X:13 Y:13",
				markerid = 8141313,
				name = "White Clay",
				okgp = 700,
				sand = 27811,
				shard = 5,
				skillname = "Collective_Default.lua",
				skillnum = 2,
				skip = false,
				sname = "Chiaroglow Aethersand",
				submarkerid = 8141413,
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 0,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27542,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:13",
				markerid = 8162013,
				name = "Voeburt Bichir",
				okgp = 0,
				sand = 27811,
				shard = 7,
				skillname = "Eph 600-800 2step-zero-eye-give-up.lua",
				skip = false,
				sname = "Chiaroglow Aethersand",
				useGift = true,
			},
			
			{
				HQamount = 0,
				amount = 0,
				c_w_cluster = false,
				c_w_crystal = false,
				c_w_sand = true,
				collect = true,
				cordial = true,
				crystal = 1,
				crystalId = 13,
				gatherNormalDo = false,
				id = 27543,
				job = 18,
				mapid = 816,
				mapname = "Il Mheg X:20 Y:22",
				markerid = 8162022,
				name = "Poecilia",
				okgp = 0,
				sand = 27812,
				shard = 7,
				skillname = "Collective_Default.lua",
				skip = true,
				sname = "Scuroglow Aethersand",
				useGift = true,
			},
		},
	},
	filename = "Sands",
	glist = 
	{
	},
	normalTimebase = 
	{
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
		
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		}, 
		[0] = 
		{
			collect = false,
			cordial = true,
			id = 0,
			job = 0,
			markerid = 0,
			okgp = 0,
			skillname = "Leveling.lua",
			skip = false,
			tasktype = "empty",
		},
	},
	normalType = "Timebase",
	orders = 
	{
	},
	unspoil = 
	{
		
		{
			HQamount = 0,
			amount = 0,
			collect = false,
			cordial = true,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 28716,
			job = 17,
			mapid = 817,
			markerid = 8172436,
			name = "Sandalwood Sap",
			okgp = 750,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			slot = 4,
			timeChecks = 
			{
				[2] = true,
				[3] = true,
				[14] = true,
				[15] = true,
			},
			timeoks = 
			{
				2,
				3,
				14,
				15,
			},
			x = 24,
			y = 36,
		},
		
		{
			HQamount = 0,
			amount = 0,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29976,
			job = 16,
			mapid = 815,
			markerid = 8152008,
			name = "Ashen Alumen",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			slot = 2,
			timeChecks = 
			{
				[10] = true,
				[11] = true,
				[22] = true,
				[23] = true,
			},
			timeoks = 
			{
				10,
				11,
				22,
				23,
			},
			x = 20,
			y = 8,
		},
		
		{
			HQamount = 0,
			amount = 0,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29972,
			job = 17,
			mapid = 816,
			markerid = 8163627,
			name = "Merbau Log",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			slot = 6,
			timeChecks = 
			{
				[8] = true,
				[9] = true,
				[20] = true,
				[21] = true,
			},
			timeoks = 
			{
				8,
				9,
				20,
				21,
			},
			x = 36,
			y = 27,
		},
		
		{
			HQamount = 0,
			amount = 0,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29970,
			job = 16,
			mapid = 818,
			markerid = 8183431,
			name = "Purpure Shell Chip",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			slot = 1,
			timeChecks = 
			{
				[6] = true,
				[7] = true,
				[18] = true,
				[19] = true,
			},
			timeoks = 
			{
				6,
				7,
				18,
				19,
			},
			x = 34,
			y = 31,
		},
		
		{
			HQamount = 0,
			amount = 0,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29974,
			job = 17,
			mapid = 815,
			markerid = 8153233,
			name = "Duskblooms",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			slot = 4,
			timeChecks = 
			{
				[4] = true,
				[5] = true,
				[16] = true,
				[17] = true,
			},
			timeoks = 
			{
				4,
				5,
				16,
				17,
			},
			x = 32,
			y = 33,
		},
		
		{
			HQamount = 0,
			amount = 0,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29968,
			job = 16,
			mapid = 813,
			markerid = 8130433,
			name = "Fireheart Cobalt",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			slot = 6,
			timeChecks = 
			{
				[2] = true,
				[3] = true,
				[14] = true,
				[15] = true,
			},
			timeoks = 
			{
				2,
				3,
				14,
				15,
			},
			x = 4,
			y = 33,
		},
		
		{
			HQamount = 0,
			amount = 0,
			collect = false,
			cordial = false,
			expansion = "Shadow",
			folklore = true,
			hold = false,
			id = 29978,
			job = 17,
			mapid = 814,
			markerid = 8142821,
			name = "Imperial Fern",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			slot = 3,
			timeChecks = 
			{
				true, 
				[0] = true,
				[12] = true,
				[13] = true,
			},
			timeoks = 
			{
				0,
				1,
				12,
				13,
			},
			x = 28,
			y = 21,
		},
		
		{
			HQamount = 0,
			amount = 0,
			collect = false,
			cordial = true,
			expansion = "Shadow",
			folklore = false,
			hold = false,
			id = 27828,
			job = 17,
			mapid = 817,
			markerid = 8173421,
			name = "Mist Spinach",
			okgp = 0,
			reserve = false,
			skillname = "Leveling.lua",
			skillnum = 8,
			skip = true,
			slot = 6,
			timeChecks = 
			{
				true, 
				[0] = true,
				[12] = true,
				[13] = true,
			},
			timeoks = 
			{
				0,
				1,
				12,
				13,
			},
			x = 34,
			y = 21,
		},
	},
	unspoilTimeline = 
	{
		
		{
			29978,
			27828,
		},
		
		{
			28716,
			29968,
		},
		
		{
			28716,
			29968,
		},
		
		{
			29974,
		},
		
		{
			29974,
		},
		
		{
			29970,
		},
		
		{
			29970,
		},
		
		{
			29972,
		},
		
		{
			29972,
		},
		
		{
			29976,
		},
		
		{
			29976,
		},
		
		{
			29978,
			27828,
		},
		
		{
			29978,
			27828,
		},
		
		{
			28716,
			29968,
		},
		
		{
			28716,
			29968,
		},
		
		{
			29974,
		},
		
		{
			29974,
		},
		
		{
			29970,
		},
		
		{
			29970,
		},
		
		{
			29972,
		},
		
		{
			29972,
		},
		
		{
			29976,
		},
		
		{
			29976,
		}, 
		[0] = 
		{
			29978,
			27828,
		},
	},
}



return tbl